public enum TypesMessage {
    DEPLACER,
    ASSECHER,
    DONNER_CARTE,
    FIN_TOUR,
    RECUPERER_TRESOR,
    UTILISER_CARTE_COURANT,
    UTILISER_CARTE_NON_COURANT,
    DEMARRER_PARTIE,
    DEPLACER_VERS,
    ASSECHER_VERS,
    ACTION_SPECIALE,
    DON_DE_CARTE,
    ASSECHER_SPECIAL,
    CARTE_HELICOPTER
}
